// Temporary stub to satisfy TS during frontend build in this environment.
// In your actual backend setup, this file will be auto-generated by Lovable Cloud.
export type Database = Record<string, never>;
